//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teploset.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutCatalog
    {
        public System.Guid AboutId { get; set; }
        public System.Guid LangTypeId { get; set; }
        public System.DateTime DateTimeOpen { get; set; }
        public System.DateTime DateTimeCreate { get; set; }
        public string Body { get; set; }
    
        public virtual LangTypeCatalog LangTypeCatalog { get; set; }
    }
}
