//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teploset.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacancyCatalog
    {
        public System.Guid VacId { get; set; }
        public System.Guid LangTypeId { get; set; }
        public System.DateTime DateTimeOpen { get; set; }
        public System.DateTime DateTimeCreate { get; set; }
        public string VacancyName { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Comment { get; set; }
    
        public virtual LangCatalog LangCatalog { get; set; }
    }
}
